api_platform:
    title: 'Symfony REST API'
    description: 'A Symfony API to manage a simple blog app.'
    version: '1.0.0'
    mapping:
        paths: [ '%kernel.project_dir%/src/Entity', '%kernel.project_dir%/config/packages/api_platform' ]
    patch_formats:
        json: [ 'application/merge-patch+json' ]
    swagger:
        versions: [ 3 ]
        api_keys:
            apiKey:
                name: Authorization
                type: header
